# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build JAR app to Docker Hub - osiris-rest-api

on:
  pull_request:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Generating JAR
        run: mvn package
        
      - name: Mostrando o Diretório
        run: ls -la target/
          
      - name: Versionamento da aplicação
        uses: brpaz/action-semantic-release@v1

      - name: Build and publish Docker Image to new GitHub Packages Registry
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: osiris-rest-api
          image-tag: ${{ GITHUB_RUN_NUMBER }}
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'localhost.com'
    needs: build
    steps:
      - name: Echo Deploy DEV
        run: echo deploy DEV
  
  deploy-hml:
    runs-on: ubuntu-latest
    environment:
      name: hml
      url: 'localhost.com'
    needs: deploy-dev
    steps:
      - name: Echo Deploy HML
        run: echo deploy HML
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'localhost.com'
    needs: deploy-hml
    steps:
      - name: Echo Deploy PROD
        run: echo deploy PROD
